[package]
name = "pve-lxc-syscalld"
edition = "2018"
version = "0.1.0"
authors = [
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
bitflags = "1.1"
failure = { version = "0.1", default-features = false, features = ["std"] }
lazy_static = "1.3"
libc = "0.2"
nix = "0.15"

[dependencies.io-uring]
version = "0.1"
path = "../io-uring"
features = ["runtime"]
