[package]
name = "pve-lxc-syscalld"
edition = "2018"
version = "0.1.0"
authors = [
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
errno = "0.2"
failure = "0.1"
libc = "0.2"
mio = "0.6"
nix = "0.14"
futures-preview = { version = "0.3.0-alpha.17", features = [ "compat", "io-compat" ] }
tokio = { version = "0.2", git = "https://github.com/tokio-rs/tokio" }
